apiVersion: v1
kind: Secret
metadata:
  name: seerr-oci-registry
  namespace: media
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: seerr-oci
  type: helm
  enableOCI: "true"
  url: ghcr.io