route:
  main:
    enabled: true
    parentRefs:
      - name: shared-gateway
        namespace: envoy-gateway-system
    hostnames:
      - seerr.larswenda.org
config:
  persistence:
    storageClass: longhorn