defaultSettings:
  defaultReplicaCount: 1
  replicaSoftAntiAffinity: true

longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

longhornUI:
  replicas: 1