apiVersion: v1
kind: Secret

metadata:
  name: envoy-helm-oci
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  name: envoy-oci
  type: helm
  enableOCI: "true"

  url: registry-1.docker.io